# Generated by Django 3.2.9 on 2022-06-09 01:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Account', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject_name', models.CharField(max_length=150)),
                ('school_hour', models.TimeField(blank=True, null=True)),
                ('subject_degree', models.FloatField()),
                ('dept', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subject', to='Account.department')),
                ('teacher', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='teacher', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SubSubject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sub_subject_name', models.CharField(max_length=150)),
                ('school_hour', models.TimeField(blank=True, null=True)),
                ('subject_degree', models.FloatField()),
                ('subject', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='SubSubject', to='Tutorial.subject')),
                ('teacher', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Teacher', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Lecture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('lecture', models.FileField(upload_to='lecture_file/')),
                ('sub_subject', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sub_subject_lecture', to='Tutorial.subsubject')),
                ('subject', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subject_lecture', to='Tutorial.subject')),
            ],
        ),
    ]
